### ISSUE TITLE
Cannot parse standard array

### ISSUE THREAD

**Issue by mrextreme** [austinhyde/IniParser#6]
Warning: array_key_exists() expects parameter 2 to be array, string given in /xxxxx/IniParser.php on line 151

Fatal error: Cannot create references to/from string offsets nor overloaded objects in /xxxxxxxxx/IniParser.php on line 158

when I use good old

a[] = 1
a[] = 2
a[] = "c"

in the INI file, while parse_ini_file() has no issues with it and gives the desired result

PHP 5.4.6, Ubuntu 12.10

**Comment by austinhyde** [comment]
Solved in commit f70e411
